export const number = [
  { EN: "one, two, three, four, five, six, seven, eight, nine, ten", JP: "一、二、三、四、五、六、七、八、九、十", CH: "一、二、三、四、五、六、七、八、九、十", KO: "하나, 둘, 셋, 넷, 다섯, 여섯, 일곱, 여덟, 아홉, 열", ES: "uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez", DE: "eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn" },
  { EN: "11 dollars.", JP: "11ドルです。", CH: "11美元。", KO: "11달러예요.", ES: "11 dólares.", DE: "11 Dollar." },
  { EN: "52 cents.", JP: "52セントです。", CH: "52美分。", KO: "52센트예요.", ES: "52 centavos.", DE: "52 Cent." },
  { EN: "A few.", JP: "いくつか。", CH: "几个。", KO: "몇 개.", ES: "Algunos.", DE: "Einige." },
  { EN: "A little.", JP: "少し。", CH: "一点。", KO: "조금.", ES: "Un poco.", DE: "Ein bisschen." },
  { EN: "Did your wife like California?", JP: "奥さんはカリフォルニアが好きでしたか？", CH: "你妻子喜欢加州吗？", KO: "당신 아내가 캘리포니아를 좋아했나요?", ES: "¿A tu esposa le gustó California?", DE: "Hat Ihre Frau Kalifornien gemocht?" },
  { EN: "Do you have any coffee?", JP: "コーヒーはありますか？", CH: "你有咖啡吗？", KO: "커피 있어요?", ES: "¿Tienes café?", DE: "Haben Sie Kaffee?" },
  { EN: "Do you have anything cheaper?", JP: "もっと安いものはありますか？", CH: "你有更便宜的吗？", KO: "더 싼 거 있어요?", ES: "¿Tienes algo más barato?", DE: "Haben Sie etwas Billigeres?" },
  { EN: "Do you take credit cards?", JP: "クレジットカードは使えますか？", CH: "你接受信用卡吗？", KO: "신용카드 되나요?", ES: "¿Aceptan tarjetas de crédito?", DE: "Akzeptieren Sie Kreditkarten?" },
  { EN: "How are you paying?", JP: "どのように支払いますか？", CH: "你怎么付款？", KO: "어떻게 결제할 거예요?", ES: "¿Cómo vas a pagar?", DE: "Wie zahlen Sie?" },
  { EN: "How many people are there in New York?", JP: "ニューヨークには何人いますか？", CH: "纽约有多少人？", KO: "뉴욕에는 몇 명 있어요?", ES: "¿Cuántas personas hay en Nueva York?", DE: "Wie viele Leute gibt es in New York?" },
  { EN: "How much are these earrings?", JP: "このイヤリングはいくらですか？", CH: "这些耳环多少钱？", KO: "이 귀걸이 얼마예요?", ES: "¿Cuánto cuestan estos pendientes?", DE: "Wie viel kosten diese Ohrringe?" },
  { EN: "How much does it cost per day?", JP: "1日いくらですか？", CH: "每天多少钱？", KO: "하루에 얼마예요?", ES: "¿Cuánto cuesta por día?", DE: "Wie viel kostet es pro Tag?" },
  { EN: "How much does this cost?", JP: "これはいくらですか？", CH: "这个多少钱？", KO: "이거 얼마예요?", ES: "¿Cuánto cuesta esto?", DE: "Wie viel kostet das?" },
  { EN: "How much do I owe you?", JP: "いくら払えばいいですか？", CH: "我欠你多少钱？", KO: "얼마를 내야 해요?", ES: "¿Cuánto te debo?", DE: "Wie viel schulde ich dir?" },
  { EN: "How much is it to go to Miami?", JP: "マイアミまでいくらですか？", CH: "去迈阿密多少钱？", KO: "마이애미까지 얼마예요?", ES: "¿Cuánto cuesta ir a Miami?", DE: "Wie viel kostet es nach Miami zu gehen?" },
  { EN: "How much money do you make?", JP: "収入はいくらですか？", CH: "你赚多少钱？", KO: "수입이 얼마예요?", ES: "¿Cuánto dinero ganas?", DE: "Wie viel Geld verdienst du?" },
  { EN: "I'd like to eat at 5th street restaurant.", JP: "5番街のレストランで食べたいです。", CH: "我想在第五街餐厅吃饭。", KO: "5번가 식당에서 먹고 싶어요.", ES: "Quisiera comer en el restaurante de la Quinta Avenida.", DE: "Ich möchte im 5th Street Restaurant essen." },
  { EN: "I don't have a girlfriend.", JP: "彼女がいません。", CH: "我没有女朋友。", KO: "여자친구 없어요.", ES: "No tengo novia.", DE: "Ich habe keine Freundin." },
  { EN: "I don't have any money.", JP: "お金がありません。", CH: "我没有钱。", KO: "돈이 없어요.", ES: "No tengo dinero.", DE: "Ich habe kein Geld." },
  { EN: "I have a reservation.", JP: "予約があります。", CH: "我有预订。", KO: "예약이 있어요.", ES: "Tengo una reserva.", DE: "Ich habe eine Reservierung." },
  { EN: "I'll have the same thing.", JP: "同じものをください。", CH: "我也要一样的。", KO: "같은 걸로 주세요.", ES: "Tomaré lo mismo.", DE: "Ich nehme dasselbe." },
  { EN: "I'll pay for dinner.", JP: "夕食は私が払います。", CH: "我来付晚餐。", KO: "저녁은 제가 낼게요.", ES: "Pagaré la cena.", DE: "Ich bezahle das Abendessen." },
  { EN: "I'll pay for the tickets.", JP: "チケットは私が払います。", CH: "我来付票。", KO: "표는 제가 낼게요.", ES: "Pagaré los boletos.", DE: "Ich bezahle die Tickets." },
  { EN: "I'm 26 years old.", JP: "私は26歳です。", CH: "我26岁。", KO: "저는 26살이에요.", ES: "Tengo 26 años.", DE: "Ich bin 26 Jahre alt." },
  { EN: "I need to practice my English.", JP: "英語を練習する必要があります。", CH: "我需要练习英语。", KO: "영어를 연습해야 해요.", ES: "Necesito practicar mi inglés.", DE: "Ich muss mein Englisch üben." },
  { EN: "Isn't it?", JP: "そうではありませんか？", CH: "不是吗？", KO: "그렇지 않나요?", ES: "¿No es así?", DE: "Nicht wahr?" },
  { EN: "Is that ok?", JP: "それで大丈夫ですか？", CH: "这样可以吗？", KO: "괜찮아요?", ES: "¿Está bien?", DE: "Ist das okay?" },
  { EN: "Is there any mail for me?", JP: "私宛の郵便物はありますか？", CH: "有我的邮件吗？", KO: "제게 온 우편물 있나요?", ES: "¿Hay correo para mí?", DE: "Gibt es Post für mich?" },
  { EN: "It's 11:30pm.", JP: "午後11時30分です。", CH: "现在是晚上11:30。", KO: "밤 11시 30분이에요.", ES: "Son las 11:30 p.m.", DE: "Es ist 23:30 Uhr." },
  { EN: "It's a quarter past nine.", JP: "9時15分です。", CH: "现在是九点一刻。", KO: "9시 15분이에요.", ES: "Son las nueve y cuarto.", DE: "Es ist Viertel nach neun." },
  { EN: "Please come in.", JP: "どうぞお入りください。", CH: "请进。", KO: "들어오세요.", ES: "Por favor, entra.", DE: "Bitte treten Sie ein." },
  { EN: "Sorry, we don't accept credit cards.", JP: "すみません、クレジットカードは使えません。", CH: "抱歉，我们不接受信用卡。", KO: "죄송하지만, 신용카드는 안 돼요.", ES: "Lo siento, no aceptamos tarjetas de crédito.", DE: "Entschuldigung, wir akzeptieren keine Kreditkarten." },
  { EN: "Sorry, we only accept Cash.", JP: "すみません、現金のみです。", CH: "抱歉，我们只接受现金。", KO: "죄송하지만 현금만 돼요.", ES: "Lo siento, solo aceptamos efectivo.", DE: "Entschuldigung, wir akzeptieren nur Bargeld." },
  { EN: "That restaurant is not expensive.", JP: "そのレストランは高くありません。", CH: "那家餐厅不贵。", KO: "그 식당은 비싸지 않아요.", ES: "Ese restaurante no es caro.", DE: "Dieses Restaurant ist nicht teuer." },
  { EN: "That's too expensive.", JP: "それは高すぎます。", CH: "那太贵了。", KO: "그거 너무 비싸요.", ES: "Eso es demasiado caro.", DE: "Das ist zu teuer." },
  { EN: "There are many people here.", JP: "ここにはたくさんの人がいます。", CH: "这里有很多人。", KO: "여기에 사람이 많아요.", ES: "Hay muchas personas aquí.", DE: "Es sind viele Leute hier." },
  { EN: "They charge 26 dollars per day.", JP: "1日26ドルです。", CH: "他们每天收26美元。", KO: "하루에 26달러예요.", ES: "Cobran 26 dólares por día.", DE: "Sie berechnen 26 Dollar pro Tag." },
  { EN: "What's the exchange rate for dollars?", JP: "ドルの為替レートはいくらですか？", CH: "美元的汇率是多少？", KO: "달러 환율이 얼마예요?", ES: "¿Cuál es el tipo de cambio del dólar?", DE: "Wie ist der Wechselkurs für Dollar?" },
  { EN: "What's the phone number?", JP: "電話番号は何ですか？", CH: "电话号码是多少？", KO: "전화번호가 뭐예요?", ES: "¿Cuál es el número de teléfono?", DE: "Wie lautet die Telefonnummer?" },
  { EN: "Where can I buy tickets?", JP: "どこでチケットを買えますか？", CH: "我在哪里可以买票？", KO: "어디서 표를 살 수 있어요?", ES: "¿Dónde puedo comprar boletos?", DE: "Wo kann ich Tickets kaufen?" },
  { EN: "Where would you like to meet?", JP: "どこで会いたいですか？", CH: "你想在哪里见面？", KO: "어디서 만날래요?", ES: "¿Dónde te gustaría reunirte?", DE: "Wo möchten Sie sich treffen?" },
  { EN: "Which one is better?", JP: "どちらがいいですか？", CH: "哪一个更好？", KO: "어느 것이 더 좋아요?", ES: "¿Cuál es mejor?", DE: "Welches ist besser?" }
];

export const location = [
  
  { EN: "Across from the post office.", JP: "郵便局の向かいです。", CH: "在邮局对面。", KO: "우체국 맞은편이에요.", ES: "Frente a la oficina de correos.", DE: "Gegenüber der Post." },
  { EN: "At 3 o'clock.", JP: "3時に。", CH: "三点。", KO: "3시에요.", ES: "A las 3 en punto.", DE: "Um 3 Uhr." },
  { EN: "Be quiet.", JP: "静かにしてください。", CH: "安静。", KO: "조용히 해요.", ES: "Cállate / Mantén silencio.", DE: "Sei ruhig." },
  { EN: "Can you recommend a good restaurant?", JP: "おすすめのレストランはありますか？", CH: "你能推荐一家好餐厅吗？", KO: "좋은 식당 추천해 줄 수 있어요?", ES: "¿Puedes recomendar un buen restaurante?", DE: "Können Sie ein gutes Restaurant empfehlen?" },
  { EN: "Here it is.", JP: "ここです。", CH: "在这里。", KO: "여기 있어요.", ES: "Aquí está.", DE: "Hier ist es." },
  { EN: "Here you are.", JP: "はい、どうぞ。", CH: "给你。", KO: "여기 있어요.", ES: "Aquí tienes.", DE: "Bitte schön." },
  { EN: "He's in the kitchen.", JP: "彼は台所にいます。", CH: "他在厨房里。", KO: "그는 부엌에 있어요.", ES: "Él está en la cocina.", DE: "Er ist in der Küche." },
  { EN: "He studies at Boston University.", JP: "彼はボストン大学で勉強しています。", CH: "他在波士顿大学学习。", KO: "그는 보스턴 대학교에서 공부해요.", ES: "Él estudia en la Universidad de Boston.", DE: "Er studiert an der Boston University." },
  { EN: "How far is it?", JP: "どのくらい遠いですか？", CH: "有多远？", KO: "얼마나 멀어요?", ES: "¿Qué tan lejos está?", DE: "Wie weit ist es?" },
  { EN: "How far is it to Chicago?", JP: "シカゴまでどのくらいですか？", CH: "到芝加哥有多远？", KO: "시카고까지 얼마나 멀어요?", ES: "¿Qué tan lejos está Chicago?", DE: "Wie weit ist es nach Chicago?" },
  { EN: "How many miles is it to Pennsylvania?", JP: "ペンシルベニアまで何マイルですか？", CH: "到宾夕法尼亚有多少英里？", KO: "펜실베이니아까지 몇 마일이에요?", ES: "¿Cuántas millas hay hasta Pennsylvania?", DE: "Wie viele Meilen sind es bis Pennsylvania?" },
  { EN: "I'd like a single room.", JP: "シングルルームをお願いします。", CH: "我想要一间单人房。", KO: "싱글룸으로 주세요.", ES: "Quisiera una habitación individual.", DE: "Ich hätte gern ein Einzelzimmer." },
  { EN: "I like to watch TV.", JP: "テレビを見るのが好きです。", CH: "我喜欢看电视。", KO: "저는 TV 보는 것을 좋아해요.", ES: "Me gusta ver la televisión.", DE: "Ich sehe gerne fern." },
  { EN: "It's delicious!", JP: "おいしいです！", CH: "很好吃！", KO: "맛있어요!", ES: "¡Está delicioso!", DE: "Es ist lecker!" },
  { EN: "It's half past 11.", JP: "11時30分です。", CH: "11点半。", KO: "11시 반이에요.", ES: "Son las 11 y media.", DE: "Es ist halb zwölf." },
  { EN: "It's less than 5 dollars.", JP: "5ドル未満です。", CH: "不到5美元。", KO: "5달러 미만이에요.", ES: "Es menos de 5 dólares.", DE: "Es ist weniger als 5 Dollar." },
  { EN: "It's more than 5 dollars.", JP: "5ドル以上です。", CH: "超过5美元。", KO: "5달러 이상이에요.", ES: "Es más de 5 dólares.", DE: "Es ist mehr als 5 Dollar." },
  { EN: "It's near the Supermarket.", JP: "スーパーマーケットの近くです。", CH: "它在超市附近。", KO: "슈퍼마켓 근처예요.", ES: "Está cerca del supermercado.", DE: "Es ist in der Nähe des Supermarkts." },
  { EN: "It's not supposed to rain today.", JP: "今日は雨の予報ではありません。", CH: "今天不应该下雨。", KO: "오늘은 비가 안 올 거예요.", ES: "No se supone que llueva hoy.", DE: "Es soll heute nicht regnen." },
  { EN: "It's ok.", JP: "大丈夫です。", CH: "没关系。", KO: "괜찮아요.", ES: "Está bien.", DE: "Es ist okay." },
  { EN: "It's on 7th street.", JP: "7番通りにあります。", CH: "它在第七街。", KO: "7번가에 있어요.", ES: "Está en la calle Séptima.", DE: "Es ist in der 7. Straße." },
  { EN: "It's really hot.", JP: "とても暑いです。", CH: "真的很热。", KO: "정말 덥네요.", ES: "Hace mucho calor.", DE: "Es ist sehr heiß." },
  { EN: "It's supposed to rain tomorrow.", JP: "明日は雨の予報です。", CH: "明天会下雨。", KO: "내일은 비가 올 예정이에요.", ES: "Se supone que lloverá mañana.", DE: "Es soll morgen regnen." },
  { EN: "I was going to the library.", JP: "私は図書館に行くところでした。", CH: "我正要去图书馆。", KO: "저는 도서관에 가려던 참이었어요.", ES: "Iba a la biblioteca.", DE: "Ich wollte in die Bibliothek gehen." },
  { EN: "I was in the library.", JP: "私は図書館にいました。", CH: "我在图书馆里。", KO: "저는 도서관에 있었어요.", ES: "Estaba en la biblioteca.", DE: "Ich war in der Bibliothek." },
  { EN: "Let's go.", JP: "行きましょう。", CH: "我们走吧。", KO: "가자.", ES: "Vamos.", DE: "Lass uns gehen." },
  { EN: "Maybe.", JP: "たぶん。", CH: "也许。", KO: "아마도.", ES: "Tal vez.", DE: "Vielleicht." },
  { EN: "More than 200 miles.", JP: "200マイル以上です。", CH: "超过200英里。", KO: "200마일 이상이에요.", ES: "Más de 200 millas.", DE: "Mehr als 200 Meilen." },
  { EN: "My house is close to the bank.", JP: "私の家は銀行の近くです。", CH: "我家离银行很近。", KO: "우리 집은 은행 가까이에 있어요.", ES: "Mi casa está cerca del banco.", DE: "Mein Haus ist in der Nähe der Bank." },
  { EN: "Near the bank.", JP: "銀行の近くです。", CH: "在银行附近。", KO: "은행 근처예요.", ES: "Cerca del banco.", DE: "In der Nähe der Bank." },
  { EN: "On the left.", JP: "左側です。", CH: "在左边。", KO: "왼쪽에 있어요.", ES: "A la izquierda.", DE: "Auf der linken Seite." },
  { EN: "On the right.", JP: "右側です。", CH: "在右边。", KO: "오른쪽에 있어요.", ES: "A la derecha.", DE: "Auf der rechten Seite." },
  { EN: "On the second floor.", JP: "2階にあります。", CH: "在二楼。", KO: "2층에 있어요.", ES: "En el segundo piso.", DE: "Im zweiten Stock." },
  { EN: "Outside the hotel.", JP: "ホテルの外です。", CH: "在酒店外面。", KO: "호텔 밖이에요.", ES: "Fuera del hotel.", DE: "Außerhalb des Hotels." },
  { EN: "Over here.", JP: "こちらです。", CH: "这里。", KO: "여기예요.", ES: "Por aquí.", DE: "Hierher." },
  { EN: "The book is behind the table.", JP: "本はテーブルの後ろにあります。", CH: "书在桌子后面。", KO: "책이 탁자 뒤에 있어요.", ES: "El libro está detrás de la mesa.", DE: "Das Buch ist hinter dem Tisch." },
  { EN: "The book is in front of the table.", JP: "本はテーブルの前にあります。", CH: "书在桌子前面。", KO: "책이 탁자 앞에 있어요.", ES: "El libro está delante de la mesa.", DE: "Das Buch ist vor dem Tisch." },
  { EN: "The book is near the table.", JP: "本はテーブルの近くにあります。", CH: "书在桌子附近。", KO: "책이 탁자 근처에 있어요.", ES: "El libro está cerca de la mesa.", DE: "Das Buch ist in der Nähe des Tisches." },
  { EN: "The book is next to the table.", JP: "本はテーブルの隣にあります。", CH: "书在桌子旁边。", KO: "책이 탁자 옆에 있어요.", ES: "El libro está al lado de la mesa.", DE: "Das Buch ist neben dem Tisch." },
  { EN: "The book is on top of the table.", JP: "本はテーブルの上にあります。", CH: "书在桌子上。", KO: "책이 탁자 위에 있어요.", ES: "El libro está encima de la mesa.", DE: "Das Buch liegt auf dem Tisch." },
  { EN: "There are some books on the table.", JP: "テーブルの上にいくつか本があります。", CH: "桌子上有一些书。", KO: "탁자 위에 책이 몇 권 있어요.", ES: "Hay algunos libros en la mesa.", DE: "Es liegen einige Bücher auf dem Tisch." },
  { EN: "There's a book under the table.", JP: "テーブルの下に本があります。", CH: "桌子下面有一本书。", KO: "탁자 밑에 책이 있어요.", ES: "Hay un libro debajo de la mesa.", DE: "Unter dem Tisch liegt ein Buch." },
  { EN: "We're from California.", JP: "私たちはカリフォルニア出身です。", CH: "我们来自加州。", KO: "우리는 캘리포니아 출신이에요.", ES: "Somos de California.", DE: "Wir kommen aus Kalifornien." },
  { EN: "What's the address?", JP: "住所は何ですか？", CH: "地址是什么？", KO: "주소가 뭐예요?", ES: "¿Cuál es la dirección?", DE: "Wie lautet die Adresse?" },
  { EN: "Where are you going?", JP: "どこに行くのですか？", CH: "你要去哪里？", KO: "어디 가요?", ES: "¿A dónde vas?", DE: "Wohin gehst du?" },
  { EN: "Where is it?", JP: "それはどこですか？", CH: "它在哪里？", KO: "그거 어디 있어요?", ES: "¿Dónde está?", DE: "Wo ist es?" },
  { EN: "Where would you like to go?", JP: "どこに行きたいですか？", CH: "你想去哪里？", KO: "어디 가고 싶어요?", ES: "¿A dónde te gustaría ir?", DE: "Wohin möchten Sie gehen?" },
  { EN: "Who won?", JP: "誰が勝ちましたか？", CH: "谁赢了？", KO: "누가 이겼어요?", ES: "¿Quién ganó?", DE: "Wer hat gewonnen?" } ,
  { EN: "Over there.", JP: "あちらです。", CH: "那里。", KO: "저기예요.", ES: "Por allí.", DE: "Dort drüben." },
];

export const contact = [
  { EN: "Can I see your passport please?", JP: "パスポートを見せていただけますか？", CH: "我可以看看你的护照吗？", KO: "여권 좀 보여주시겠어요?", ES: "¿Puedo ver su pasaporte, por favor?", DE: "Kann ich bitte Ihren Pass sehen?" },
  { EN: "Can I take a message?", JP: "伝言をお預かりしましょうか？", CH: "我可以帮你留言吗？", KO: "메시지 받아드릴까요?", ES: "¿Puedo tomar un mensaje?", DE: "Kann ich eine Nachricht entgegennehmen?" },
  { EN: "Can I try it on?", JP: "試着してもいいですか？", CH: "我可以试穿吗？", KO: "입어봐도 돼요?", ES: "¿Puedo probármelo?", DE: "Kann ich es anprobieren?" },
  { EN: "Can we sit over there?", JP: "あそこに座ってもいいですか？", CH: "我们可以坐在那里吗？", KO: "저쪽에 앉아도 될까요?", ES: "¿Podemos sentarnos allí?", DE: "Können wir dort sitzen?" },
  { EN: "Did you come with your family?", JP: "ご家族と一緒に来ましたか？", CH: "你和家人一起来的吗？", KO: "가족과 함께 왔어요?", ES: "¿Viniste con tu familia?", DE: "Kommen Sie mit Ihrer Familie?" },
  { EN: "Do you think it's possible?", JP: "可能だと思いますか？", CH: "你觉得可能吗？", KO: "가능하다고 생각해요?", ES: "¿Crees que es posible?", DE: "Glauben Sie, dass es möglich ist?" },
  { EN: "Here's my number.", JP: "これが私の番号です。", CH: "这是我的号码。", KO: "제 번호예요.", ES: "Aquí está mi número.", DE: "Hier ist meine Nummer." },
  { EN: "He's not in right now.", JP: "彼は今席を外しています。", CH: "他现在不在。", KO: "그는 지금 없어요.", ES: "Él no está ahora.", DE: "Er ist gerade nicht da." },
  { EN: "Hi, is Mrs. Smith there, please?", JP: "もしもし、スミスさんはいらっしゃいますか？", CH: "你好，请问史密斯女士在吗？", KO: "안녕하세요, 스미스 부인 계신가요?", ES: "Hola, ¿está la señora Smith?", DE: "Hallo, ist Frau Smith da?" },
  { EN: "I'd like some water too, please.", JP: "私も水をください。", CH: "我也想要一些水。", KO: "저도 물 주세요.", ES: "También me gustaría un poco de agua, por favor.", DE: "Ich hätte auch gerne etwas Wasser, bitte." },
  { EN: "I'd like to buy a bottle of water, please.", JP: "水のボトルを買いたいです。", CH: "我想买一瓶水。", KO: "물 한 병 사고 싶어요.", ES: "Quisiera comprar una botella de agua, por favor.", DE: "Ich möchte bitte eine Flasche Wasser kaufen." },
  { EN: "I'd like to buy something.", JP: "何か買いたいです。", CH: "我想买点东西。", KO: "뭔가 사고 싶어요.", ES: "Quisiera comprar algo.", DE: "Ich möchte etwas kaufen." },
  { EN: "I'd like to go to the store.", JP: "お店に行きたいです。", CH: "我想去商店。", KO: "가게에 가고 싶어요.", ES: "Quisiera ir a la tienda.", DE: "Ich möchte zum Laden gehen." },
  { EN: "I'd like to rent a car.", JP: "車を借りたいです。", CH: "我想租一辆车。", KO: "차를 빌리고 싶어요.", ES: "Quisiera alquilar un coche.", DE: "Ich möchte ein Auto mieten." },
  { EN: "I'd like to send a fax.", JP: "ファックスを送りたいです。", CH: "我想发传真。", KO: "팩스를 보내고 싶어요.", ES: "Quisiera enviar un fax.", DE: "Ich möchte ein Fax senden." },
  { EN: "I'd like to send this to America.", JP: "これをアメリカに送りたいです。", CH: "我想把这个寄到美国。", KO: "이거 미국으로 보내고 싶어요.", ES: "Quisiera enviar esto a Estados Unidos.", DE: "Ich möchte dies nach Amerika schicken." },
  { EN: "I'd like to speak to Mr. Smith please.", JP: "スミスさんと話したいです。", CH: "我想和史密斯先生说话。", KO: "스미스 씨와 통화하고 싶어요.", ES: "Quisiera hablar con el señor Smith, por favor.", DE: "Ich möchte bitte mit Herrn Smith sprechen." },
  { EN: "I have three children, two girls and one boy.", JP: "子供が3人います。女の子2人、男の子1人です。", CH: "我有三个孩子，两个女孩一个男孩。", KO: "아이 세 명 있어요. 여자 둘, 남자 하나.", ES: "Tengo tres hijos, dos niñas y un niño.", DE: "Ich habe drei Kinder, zwei Mädchen und einen Jungen." },
  { EN: "I'll be right back.", JP: "すぐ戻ります。", CH: "我马上回来。", KO: "곧 돌아올게요.", ES: "Vuelvo enseguida.", DE: "Ich bin gleich zurück." },
  { EN: "I'll call back later.", JP: "後でかけ直します。", CH: "我稍后再打。", KO: "나중에 다시 전화할게요.", ES: "Llamaré más tarde.", DE: "Ich rufe später zurück." },
  { EN: "I'll call you on Friday.", JP: "金曜日に電話します。", CH: "我星期五给你打电话。", KO: "금요일에 전화할게요.", ES: "Te llamaré el viernes.", DE: "Ich rufe Sie am Freitag an." },
  { EN: "I'll teach you.", JP: "教えます。", CH: "我会教你。", KO: "가르쳐 줄게요.", ES: "Te enseñaré.", DE: "Ich werde dich unterrichten." },
  { EN: "I'm ok.", JP: "大丈夫です。", CH: "我没事。", KO: "괜찮아요.", ES: "Estoy bien.", DE: "Mir geht es gut." },
  { EN: "I need some tissues.", JP: "ティッシュが必要です。", CH: "我需要一些纸巾。", KO: "휴지가 필요해요.", ES: "Necesito algunos pañuelos.", DE: "Ich brauche ein paar Taschentücher." },
  { EN: "Is there an English speaking guide?", JP: "英語を話せるガイドはいますか？", CH: "有会说英语的导游吗？", KO: "영어 할 줄 아는 가이드 있어요?", ES: "¿Hay un guía que hable inglés?", DE: "Gibt es einen Englisch sprechenden Reiseführer?" },
  { EN: "I want to give you a gift.", JP: "あなたにプレゼントをあげたいです。", CH: "我想送你一份礼物。", KO: "선물을 주고 싶어요.", ES: "Quiero darte un regalo.", DE: "Ich möchte dir ein Geschenk geben." },
  { EN: "Male or female?", JP: "男性ですか、女性ですか？", CH: "男的还是女的？", KO: "남자예요, 여자예요?", ES: "¿Hombre o mujer?", DE: "Männlich oder weiblich?" },
  { EN: "My cell phone doesn't have good reception.", JP: "携帯の電波が悪いです。", CH: "我的手机信号不好。", KO: "핸드폰 신호가 안 좋아요.", ES: "Mi celular no tiene buena señal.", DE: "Mein Handy hat keinen guten Empfang." },
  { EN: "My cell phone doesn't work.", JP: "携帯が動きません。", CH: "我的手机坏了。", KO: "핸드폰이 안 돼요.", ES: "Mi celular no funciona.", DE: "Mein Handy funktioniert nicht." },
  { EN: "Please take off your shoes.", JP: "靴を脱いでください。", CH: "请脱鞋。", KO: "신발 벗어 주세요.", ES: "Por favor, quítese los zapatos.", DE: "Bitte ziehen Sie Ihre Schuhe aus." },
  { EN: "Sorry, I think I have the wrong number.", JP: "すみません、間違い電話だと思います。", CH: "对不起，我打错了。", KO: "죄송한데, 잘못 걸었어요.", ES: "Lo siento, creo que tengo el número equivocado.", DE: "Entschuldigung, ich glaube, ich habe die falsche Nummer." },
  { EN: "What is the area code?", JP: "市外局番は何ですか？", CH: "区号是多少？", KO: "지역번호가 뭐예요?", ES: "¿Cuál es el código de área?", DE: "Wie ist die Vorwahl?" },
  { EN: "What's the name of the company you work for?", JP: "あなたの会社の名前は何ですか？", CH: "你工作的公司叫什么名字？", KO: "당신이 다니는 회사 이름이 뭐예요?", ES: "¿Cuál es el nombre de la empresa en la que trabajas?", DE: "Wie heißt die Firma, für die Sie arbeiten?" },
  { EN: "What's wrong?", JP: "どうしたんですか？", CH: "怎么了？", KO: "무슨 일이에요?", ES: "¿Qué pasa?", DE: "Was ist los?" },
  { EN: "What's your address?", JP: "あなたの住所は何ですか？", CH: "你的地址是什么？", KO: "주소가 뭐예요?", ES: "¿Cuál es tu dirección?", DE: "Wie lautet Ihre Adresse?" },
  { EN: "Where can I find a hospital?", JP: "病院はどこですか？", CH: "我在哪里可以找到医院？", KO: "병원이 어디 있어요?", ES: "¿Dónde puedo encontrar un hospital?", DE: "Wo finde ich ein Krankenhaus?" },
  { EN: "Where's the closest restaurant?", JP: "一番近いレストランはどこですか？", CH: "最近的餐厅在哪里？", KO: "가장 가까운 식당이 어디예요?", ES: "¿Dónde está el restaurante más cercano?", DE: "Wo ist das nächste Restaurant?" },
  { EN: "Where's the pharmacy?", JP: "薬局はどこですか？", CH: "药店在哪里？", KO: "약국이 어디예요?", ES: "¿Dónde está la farmacia?", DE: "Wo ist die Apotheke?" },
  { EN: "Who are you?", JP: "あなたは誰ですか？", CH: "你是谁？", KO: "당신 누구예요?", ES: "¿Quién eres?", DE: "Wer sind Sie?" },
  { EN: "Who is that?", JP: "あの人は誰ですか？", CH: "那是谁？", KO: "저 사람 누구예요?", ES: "¿Quién es ese?", DE: "Wer ist das?" },
  { EN: "Who would you like to speak to?", JP: "誰と話したいですか？", CH: "你想和谁说话？", KO: "누구와 통화하고 싶어요?", ES: "¿Con quién le gustaría hablar?", DE: "Mit wem möchten Sie sprechen?" },
  { EN: "Will you take me home?", JP: "家まで送ってくれますか？", CH: "你会送我回家吗？", KO: "집까지 데려다 줄래요?", ES: "¿Me llevarías a casa?", DE: "Bringst du mich nach Hause?" },
  { EN: "Would you like water or milk?", JP: "水か牛乳はどちらがいいですか？", CH: "你想要水还是牛奶？", KO: "물이나 우유 중 어떤 걸 원하세요?", ES: "¿Quieres agua o leche?", DE: "Möchten Sie Wasser oder Milch?" }
];

export const time = [
  { EN: "11 days ago.", JP: "11日前。", CH: "11天前。", KO: "11일 전.", ES: "Hace 11 días.", DE: "Vor 11 Tagen." },
  { EN: "2 hours.", JP: "2時間。", CH: "2小时。", KO: "2시간.", ES: "2 horas.", DE: "2 Stunden." },
  { EN: "All day.", JP: "一日中。", CH: "一整天。", KO: "하루 종일.", ES: "Todo el día.", DE: "Den ganzen Tag." },
  { EN: "A long time ago.", JP: "ずっと前。", CH: "很久以前。", KO: "오래전에.", ES: "Hace mucho tiempo.", DE: "Vor langer Zeit." },
  { EN: "Are they coming this evening?", JP: "今晩来ますか？", CH: "他们今晚会来吗？", KO: "그들은 오늘 저녁에 올까요?", ES: "¿Vendrán esta noche?", DE: "Kommen sie heute Abend?" },
  { EN: "Are you comfortable?", JP: "快適ですか？", CH: "你舒服吗？", KO: "편하세요?", ES: "¿Está cómodo?", DE: "Sind Sie bequem?" },
  { EN: "Are your children with you?", JP: "お子さんは一緒ですか？", CH: "你的孩子在你身边吗？", KO: "아이들이 함께 있어요?", ES: "¿Tus hijos están contigo?", DE: "Sind Ihre Kinder bei Ihnen?" },
  { EN: "As soon as possible.", JP: "できるだけ早く。", CH: "尽快。", KO: "가능한 빨리.", ES: "Lo antes posible.", DE: "So schnell wie möglich." },
  { EN: "At 3 o'clock in the afternoon.", JP: "午後3時に。", CH: "下午3点。", KO: "오후 3시에.", ES: "A las 3 de la tarde.", DE: "Um 15 Uhr." },
  { EN: "At 5th street.", JP: "5番街で。", CH: "在第五街。", KO: "5번가에서.", ES: "En la Quinta Avenida.", DE: "In der 5. Straße." },
  { EN: "At 7 o'clock at night. (evening)?", JP: "夜7時に。", CH: "晚上7点。", KO: "저녁 7시에.", ES: "A las 7 de la noche.", DE: "Um 19 Uhr." },
  { EN: "At 7 o'clock in the morning.", JP: "朝7時に。", CH: "早上7点。", KO: "아침 7시에.", ES: "A las 7 de la mañana.", DE: "Um 7 Uhr morgens." },
  { EN: "At what time did it happen?", JP: "それは何時に起こりましたか？", CH: "这是什么时候发生的？", KO: "몇 시에 일어났어요?", ES: "¿A qué hora pasó?", DE: "Um wie viel Uhr ist es passiert?" },
  { EN: "Can I help you?", JP: "お手伝いしましょうか？", CH: "我可以帮你吗？", KO: "도와드릴까요?", ES: "¿Puedo ayudarte?", DE: "Kann ich Ihnen helfen?" },
  { EN: "Do you have a swimming pool?", JP: "プールはありますか？", CH: "你们有游泳池吗？", KO: "수영장 있어요?", ES: "¿Tienes piscina?", DE: "Haben Sie ein Schwimmbad?" },
  { EN: "Do you have this in size 11?", JP: "これはサイズ11がありますか？", CH: "有11号吗？", KO: "이거 사이즈 11 있어요?", ES: "¿Tienes esto en talla 11?", DE: "Haben Sie das in Größe 11?" },
  { EN: "Do you think you'll be back by 11:30?", JP: "11時30分までに戻れそうですか？", CH: "你认为你能在11:30回来吗？", KO: "11:30까지 돌아올 수 있을까요?", ES: "¿Crees que volverás antes de las 11:30?", DE: "Glauben Sie, dass Sie bis 11:30 zurück sind?" },
  { EN: "Everyday I get up at 6AM.", JP: "毎日午前6時に起きます。", CH: "我每天早上6点起床。", KO: "매일 오전 6시에 일어나요.", ES: "Todos los días me levanto a las 6 a.m.", DE: "Jeden Tag stehe ich um 6 Uhr auf." },
  { EN: "Every week.", JP: "毎週。", CH: "每周。", KO: "매주.", ES: "Cada semana.", DE: "Jede Woche." },
  { EN: "Expiration date.", JP: "有効期限。", CH: "有效日期。", KO: "유효기간.", ES: "Fecha de caducidad.", DE: "Ablaufdatum." },
  { EN: "Have you been waiting long?", JP: "長く待っていますか？", CH: "你等很久了吗？", KO: "오래 기다렸어요?", ES: "¿Has estado esperando mucho?", DE: "Haben Sie lange gewartet?" },
  { EN: "He'll be back in 20 minutes.", JP: "20分で戻ります。", CH: "他20分钟后回来。", KO: "그는 20분 후에 돌아올 거예요.", ES: "Él volverá en 20 minutos.", DE: "Er wird in 20 Minuten zurück sein." },
  { EN: "His family is coming tomorrow.", JP: "彼の家族は明日来ます。", CH: "他的家人明天来。", KO: "그의 가족이 내일 와요.", ES: "Su familia viene mañana.", DE: "Seine Familie kommt morgen." },
  { EN: "How about Saturday?", JP: "土曜日はどうですか？", CH: "星期六怎么样？", KO: "토요일은 어때요?", ES: "¿Qué tal el sábado?", DE: "Wie wäre es am Samstag?" },
  { EN: "How long are you going to stay?", JP: "どのくらい滞在しますか？", CH: "你打算待多久？", KO: "얼마나 오래 머무를 거예요?", ES: "¿Cuánto tiempo vas a quedarte?", DE: "Wie lange wirst du bleiben?" },
  { EN: "How long are you going to stay in California?", JP: "カリフォルニアにはどのくらい滞在しますか？", CH: "你打算在加州待多久？", KO: "캘리포니아에 얼마나 머무를 거예요?", ES: "¿Cuánto tiempo vas a quedarte en California?", DE: "Wie lange wirst du in Kalifornien bleiben?" },
  { EN: "How long will it take?", JP: "どのくらいかかりますか？", CH: "需要多长时间？", KO: "얼마나 걸릴 거예요?", ES: "¿Cuánto tiempo tomará?", DE: "Wie lange wird es dauern?" },
  { EN: "How much altogether?", JP: "全部でいくらですか？", CH: "总共多少钱？", KO: "합계 얼마예요?", ES: "¿Cuánto es en total?", DE: "Wie viel kostet alles zusammen?" },
  { EN: "How much will it cost?", JP: "いくらかかりますか？", CH: "这要多少钱？", KO: "얼마예요?", ES: "¿Cuánto costará?", DE: "Wie viel wird es kosten?" },
  { EN: "I don't have enough money.", JP: "お金が足りません。", CH: "我没有足够的钱。", KO: "돈이 충분하지 않아요.", ES: "No tengo suficiente dinero.", DE: "Ich habe nicht genug Geld." },
  { EN: "I'm getting ready to go out.", JP: "出かける準備をしています。", CH: "我正准备出去。", KO: "나갈 준비 하고 있어요.", ES: "Me estoy preparando para salir.", DE: "Ich mache mich fertig, um rauszugehen." },
  { EN: "I'm just looking. (Shopping)", JP: "見ているだけです。", CH: "我只是看看。", KO: "그냥 보고 있어요.", ES: "Solo estoy mirando.", DE: "Ich schaue mich nur um." },
  { EN: "I'm worried too.", JP: "私も心配です。", CH: "我也很担心。", KO: "저도 걱정돼요.", ES: "Yo también estoy preocupado.", DE: "Ich mache mir auch Sorgen." },
  { EN: "It'll be cold this evening.", JP: "今晩は寒くなります。", CH: "今晚会很冷。", KO: "오늘 저녁에는 추울 거예요.", ES: "Harà frío esta noche.", DE: "Heute Abend wird es kalt sein." },
  { EN: "It rained very hard today.", JP: "今日は大雨でした。", CH: "今天下大雨。", KO: "오늘 비가 많이 왔어요.", ES: "Hoy llovió mucho.", DE: "Heute hat es stark geregnet." },
  { EN: "It's 17 dollars.", JP: "17ドルです。", CH: "17美元。", KO: "17달러예요.", ES: "Son 17 dólares.", DE: "Es kostet 17 Dollar." },
  { EN: "It's 6AM.", JP: "午前6時です。", CH: "现在是早上6点。", KO: "지금 6시예요.", ES: "Son las 6 a.m.", DE: "Es ist 6 Uhr morgens." },
  { EN: "It's 8:45.", JP: "8時45分です。", CH: "现在是8:45。", KO: "8시 45분이에요.", ES: "Son las 8:45.", DE: "Es ist 8:45." },
  { EN: "It's a quarter to 7.", JP: "7時15分前です。", CH: "差一刻七点。", KO: "7시 15분 전이에요.", ES: "Faltan quince para las 7.", DE: "Es ist Viertel vor sieben." },
  { EN: "It's going to snow today.", JP: "今日は雪が降りそうです。", CH: "今天会下雪。", KO: "오늘 눈 올 거예요.", ES: "Hoy va a nevar.", DE: "Heute wird es schneien." },
  { EN: "It's here.", JP: "ここにあります。", CH: "它在这里。", KO: "여기 있어요.", ES: "Está aquí.", DE: "Es ist hier." },
  { EN: "It's there.", JP: "あそこにあります。", CH: "它在那里。", KO: "저기 있어요.", ES: "Está allí.", DE: "Es ist dort." },
  { EN: "I've already seen it.", JP: "もう見ました。", CH: "我已经看过了。", KO: "이미 봤어요.", ES: "Ya lo he visto.", DE: "Ich habe es schon gesehen." },
  { EN: "John is going on vacation tomorrow.", JP: "ジョンは明日休暇に行きます。", CH: "约翰明天去度假。", KO: "존은 내일 휴가 가요.", ES: "John se va de vacaciones mañana.", DE: "John fährt morgen in den Urlaub." },
  { EN: "My birthday is August 27th.", JP: "私の誕生日は8月27日です。", CH: "我的生日是8月27日。", KO: "제 생일은 8월 27일이에요.", ES: "Mi cumpleaños es el 27 de agosto.", DE: "Mein Geburtstag ist am 27. August." },
  { EN: "Now or later?", JP: "今ですか、それとも後でですか？", CH: "现在还是以后？", KO: "지금이요, 나중이요?", ES: "¿Ahora o más tarde?", DE: "Jetzt oder später?" },
  { EN: "October 22nd.", JP: "10月22日。", CH: "10月22日。", KO: "10월 22일.", ES: "22 de octubre.", DE: "22. Oktober." },
  { EN: "She wants to know when you're coming.", JP: "彼女はあなたがいつ来るか知りたいです。", CH: "她想知道你什么时候来。", KO: "그녀는 당신이 언제 오는지 알고 싶어해요.", ES: "Ella quiere saber cuándo vienes.", DE: "Sie möchte wissen, wann Sie kommen." },
  { EN: "Sometimes I go to sleep at 11PM, sometimes at 11:30PM.", JP: "時々午後11時に寝ることも、午後11時30分に寝ることもあります。", CH: "有时我11点睡，有时11:30睡。", KO: "가끔 11시에 자고, 가끔 11시 30분에 자요.", ES: "A veces me acuesto a las 11PM, a veces a las 11:30PM.", DE: "Manchmal gehe ich um 23 Uhr schlafen, manchmal um 23:30." },
  { EN: "There's plenty of time.", JP: "時間はたっぷりあります。", CH: "时间很充足。", KO: "시간 충분해요.", ES: "Hay mucho tiempo.", DE: "Es gibt genug Zeit." },
  { EN: "The whole day.", JP: "一日中。", CH: "整天。", KO: "하루 종일.", ES: "Todo el día.", DE: "Den ganzen Tag." },
  { EN: "We're late.", JP: "遅れています。", CH: "我们迟到了。", KO: "우리는 늦었어요.", ES: "Estamos tarde.", DE: "Wir sind spät dran." },
  { EN: "What day are they coming over?", JP: "彼らは何曜日に来ますか？", CH: "他们哪天过来？", KO: "그들은 무슨 요일에 올 거예요?", ES: "¿Qué día vienen?", DE: "An welchem Tag kommen sie vorbei?" },
  { EN: "What day of the week is it?", JP: "今日は何曜日ですか？", CH: "今天星期几？", KO: "오늘 무슨 요일이에요?", ES: "¿Qué día de la semana es?", DE: "Welcher Wochentag ist heute?" },
  { EN: "What is today's date?", JP: "今日は何日ですか？", CH: "今天几号？", KO: "오늘 날짜가 뭐예요?", ES: "¿Cuál es la fecha de hoy?", DE: "Welches Datum ist heute?" },
  { EN: "What's your religion?", JP: "あなたの宗教は何ですか？", CH: "你的宗教信仰是什么？", KO: "종교가 뭐예요?", ES: "¿Cuál es tu religión?", DE: "Was ist Ihre Religion?" },
  { EN: "What time are they arriving?", JP: "彼らは何時に到着しますか？", CH: "他们什么时候到达？", KO: "그들은 몇 시에 도착해요?", ES: "¿A qué hora llegan?", DE: "Um wie viel Uhr kommen sie an?" },
  { EN: "What time did you get up?", JP: "何時に起きましたか？", CH: "你几点起床的？", KO: "몇 시에 일어났어요?", ES: "¿A qué hora te levantaste?", DE: "Um wie viel Uhr bist du aufgestanden?" },
  { EN: "What time did you go to sleep?", JP: "何時に寝ましたか？", CH: "你什么时候睡的？", KO: "몇 시에 잤어요?", ES: "¿A qué hora te acostaste?", DE: "Um wie viel Uhr bist du schlafen gegangen?" },
  { EN: "What time did you wake up?", JP: "何時に目が覚めましたか？", CH: "你什么时候醒的？", KO: "몇 시에 깼어요?", ES: "¿A qué hora te despertaste?", DE: "Um wie viel Uhr bist du aufgewacht?" },
  { EN: "What time does it start?", JP: "何時に始まりますか？", CH: "什么时候开始？", KO: "몇 시에 시작해요?", ES: "¿A qué hora empieza?", DE: "Wann beginnt es?" },
  { EN: "What time do you think you'll arrive?", JP: "何時に到着すると思いますか？", CH: "你认为什么时候到达？", KO: "몇 시에 도착할 거 같아요?", ES: "¿A qué hora crees que llegarás?", DE: "Um wie viel Uhr denkst du, wirst du ankommen?" },
  { EN: "What time is it?", JP: "今何時ですか？", CH: "现在几点了？", KO: "지금 몇 시예요?", ES: "¿Qué hora es?", DE: "Wie spät ist es?" },
  { EN: "When are they coming?", JP: "彼らはいつ来ますか？", CH: "他们什么时候来？", KO: "그들은 언제 올 거예요?", ES: "¿Cuándo vienen?", DE: "Wann kommen sie?" },
  { EN: "When are you coming back?", JP: "いつ戻りますか？", CH: "你什么时候回来？", KO: "언제 돌아올 거예요?", ES: "¿Cuándo vuelves?", DE: "Wann kommst du zurück?" },
  { EN: "When are you going to pick up your friend?", JP: "いつ友達を迎えに行きますか？", CH: "你什么时候去接你的朋友？", KO: "언제 친구를 데리러 갈 거예요?", ES: "¿Cuándo vas a recoger a tu amigo?", DE: "Wann holst du deinen Freund ab?" },
  { EN: "When are you leaving?", JP: "いつ出発しますか？", CH: "你什么时候离开？", KO: "언제 떠나요?", ES: "¿Cuándo te vas?", DE: "Wann gehst du?" },
  { EN: "When are you moving?", JP: "いつ引っ越しますか？", CH: "你什么时候搬家？", KO: "언제 이사해요?", ES: "¿Cuándo te mudas?", DE: "Wann ziehst du um?" },
  { EN: "When is the next bus to Philidalphia?", JP: "次のフィラデルフィア行きのバスはいつですか？", CH: "去费城的下一班公交什么时候？", KO: "다음 필라델피아행 버스는 언제예요?", ES: "¿Cuándo es el próximo autobús a Filadelfia?", DE: "Wann fährt der nächste Bus nach Philadelphia?" },
  { EN: "When is your birthday?", JP: "あなたの誕生日はいつですか？", CH: "你的生日是什么时候？", KO: "생일이 언제예요?", ES: "¿Cuándo es tu cumpleaños?", DE: "Wann hast du Geburtstag?" },
  { EN: "When I went to the store, they didn't have any apples.", JP: "私が店に行ったとき、リンゴはありませんでした。", CH: "我去商店时，他们没有苹果。", KO: "내가 가게에 갔을 때 사과가 없었어요.", ES: "Cuando fui a la tienda, no tenían manzanas.", DE: "Als ich zum Laden ging, hatten sie keine Äpfel." },
  { EN: "When was the last time you talked to your mother?", JP: "最後にお母さんと話したのはいつですか？", CH: "你上次和你妈妈说话是什么时候？", KO: "마지막으로 엄마와 이야기한 게 언제예요?", ES: "¿Cuándo fue la última vez que hablaste con tu madre?", DE: "Wann hast du das letzte Mal mit deiner Mutter gesprochen?" },
  { EN: "When will he be back?", JP: "彼はいつ戻りますか？", CH: "他什么时候回来？", KO: "그는 언제 돌아올 거예요?", ES: "¿Cuándo volverá?", DE: "Wann wird er zurück sein?" },
  { EN: "When will it be ready?", JP: "それはいつ準備できますか？", CH: "什么时候准备好？", KO: "언제 준비될 거예요?", ES: "¿Cuándo estará listo?", DE: "Wann wird es fertig sein?" },
  { EN: "Where are you going to go?", JP: "どこに行くつもりですか？", CH: "你打算去哪？", KO: "어디로 갈 거예요?", ES: "¿A dónde vas a ir?", DE: "Wohin wirst du gehen?" }
];

export const accommodations = [
  { EN: "Are you busy?", JP: "忙しいですか？", CH: "你忙吗？", KO: "바쁘세요?", ES: "¿Estás ocupado?", DE: "Bist du beschäftigt?" },
  { EN: "Can we have some more bread please?", JP: "もう少しパンをいただけますか？", CH: "我们可以再要些面包吗？", KO: "빵 좀 더 주시겠어요?", ES: "¿Podemos tener más pan, por favor?", DE: "Können wir bitte noch etwas Brot haben?" },
  { EN: "Do you have any money?", JP: "お金はありますか？", CH: "你有钱吗？", KO: "돈 있어요?", ES: "¿Tienes dinero?", DE: "Haben Sie Geld?" },
  { EN: "For how many nights?", JP: "何泊ですか？", CH: "住几晚？", KO: "몇 박이세요?", ES: "¿Por cuántas noches?", DE: "Für wie viele Nächte?" },
  { EN: "How long will you be staying?", JP: "どのくらい滞在しますか？", CH: "你打算待多久？", KO: "얼마나 오래 머무를 거예요?", ES: "¿Cuánto tiempo se va a quedar?", DE: "Wie lange werden Sie bleiben?" },
  { EN: "I'd like a map of the city.", JP: "市内の地図をください。", CH: "我想要一张城市地图。", KO: "도시 지도를 주세요.", ES: "Quisiera un mapa de la ciudad.", DE: "Ich hätte gerne eine Stadtkarte." },
  { EN: "I'd like a non-smoking room.", JP: "禁煙ルームをお願いします。", CH: "我想要一个无烟房间。", KO: "금연실로 주세요.", ES: "Quisiera una habitación para no fumadores.", DE: "Ich hätte gerne ein Nichtraucherzimmer." },
  { EN: "I'd like a room.", JP: "部屋をお願いします。", CH: "我想要一个房间。", KO: "방 하나 주세요.", ES: "Quisiera una habitación.", DE: "Ich hätte gerne ein Zimmer." },
  { EN: "I'd like a room with two beds please.", JP: "ベッドが二つある部屋をお願いします。", CH: "我想要一个有两张床的房间。", KO: "침대 두 개 있는 방으로 주세요.", ES: "Quisiera una habitación con dos camas, por favor.", DE: "Ich hätte gerne ein Zimmer mit zwei Betten." },
  { EN: "I need a doctor.", JP: "医者が必要です。", CH: "我需要一个医生。", KO: "의사가 필요해요.", ES: "Necesito un médico.", DE: "Ich brauche einen Arzt." },
  { EN: "Is there a nightclub in town?", JP: "街にナイトクラブはありますか？", CH: "镇上有夜总会吗？", KO: "이 도시에 나이트클럽 있나요?", ES: "¿Hay un club nocturno en la ciudad?", DE: "Gibt es einen Nachtclub in der Stadt?" },
  { EN: "Is there a restaurant in the hotel?", JP: "ホテルにレストランはありますか？", CH: "酒店里有餐厅吗？", KO: "호텔에 레스토랑이 있나요?", ES: "¿Hay un restaurante en el hotel?", DE: "Gibt es ein Restaurant im Hotel?" },
  { EN: "Is there a store near here?", JP: "近くにお店はありますか？", CH: "这里附近有商店吗？", KO: "여기 근처에 가게 있나요?", ES: "¿Hay una tienda cerca de aquí?", DE: "Gibt es hier in der Nähe ein Geschäft?" },
  { EN: "Sorry, we don't have any vacancies.", JP: "すみません、空きはありません。", CH: "抱歉，我们没有空房。", KO: "죄송하지만, 빈 방이 없어요.", ES: "Lo siento, no tenemos habitaciones disponibles.", DE: "Entschuldigung, wir haben keine freien Zimmer." },
  { EN: "Take me to the Marriott Hotel.", JP: "マリオットホテルまでお願いします。", CH: "请带我去万豪酒店。", KO: "메리어트 호텔로 가주세요.", ES: "Llévame al Hotel Marriott.", DE: "Bringen Sie mich bitte zum Marriott Hotel." },
  { EN: "What's the charge per night? (Hotel)", JP: "1泊いくらですか？", CH: "每晚收费多少？", KO: "1박 요금이 얼마예요?", ES: "¿Cuánto cuesta por noche?", DE: "Wie viel kostet es pro Nacht?" },
  { EN: "What time is check out?", JP: "チェックアウトは何時ですか？", CH: "退房时间是几点？", KO: "체크아웃 시간이 언제예요?", ES: "¿A qué hora es el check-out?", DE: "Wann ist der Check-out?" },
  { EN: "Where is the airport?", JP: "空港はどこですか？", CH: "机场在哪里？", KO: "공항이 어디예요?", ES: "¿Dónde está el aeropuerto?", DE: "Wo ist der Flughafen?" },
  { EN: "Where's the mail box?", JP: "郵便ポストはどこですか？", CH: "邮箱在哪里？", KO: "우체통이 어디예요?", ES: "¿Dónde está el buzón?", DE: "Wo ist der Briefkasten?" }
];
