export const greetings = [
  {
    EN: "Good afternoon.",
    CH: "下午好。",
    JP: "こんにちは。",
    KO: "좋은 오후입니다.",
    ES: "Buenas tardes.",
    DE: "Guten Nachmittag."
  },
  {
    EN: "Good evening sir.",
    CH: "晚上好，先生。",
    JP: "こんばんは、先生。",
    KO: "좋은 저녁입니다, 선생님.",
    ES: "Buenas noches, señor.",
    DE: "Guten Abend, Herr."
  },
  {
    EN: "Good Luck.",
    CH: "祝你好运。",
    JP: "頑張って。",
    KO: "행운을 빕니다.",
    ES: "Buena suerte.",
    DE: "Viel Glück."
  },
  {
    EN: "Good morning.",
    CH: "早上好。",
    JP: "おはようございます。",
    KO: "좋은 아침입니다.",
    ES: "Buenos días.",
    DE: "Guten Morgen."
  },
  {
    EN: "Great.",
    CH: "太好了。",
    JP: "素晴らしい。",
    KO: "좋아요.",
    ES: "Genial.",
    DE: "Großartig."
  },
  {
    EN: "Happy Birthday.",
    CH: "生日快乐。",
    JP: "お誕生日おめでとうございます。",
    KO: "생일 축하합니다.",
    ES: "Feliz cumpleaños.",
    DE: "Alles Gute zum Geburtstag."
  },
  {
    EN: "Have a good trip.",
    CH: "旅途愉快。",
    JP: "良い旅を。",
    KO: "좋은 여행 되세요.",
    ES: "Que tengas un buen viaje.",
    DE: "Gute Reise."
  },
  {
    EN: "Hello.",
    CH: "你好。",
    JP: "こんにちは。",
    KO: "안녕하세요.",
    ES: "Hola.",
    DE: "Hallo."
  },
  {
    EN: "Nice to meet you.",
    CH: "很高兴见到你。",
    JP: "はじめまして。",
    KO: "만나서 반갑습니다.",
    ES: "Mucho gusto.",
    DE: "Freut mich, Sie kennenzulernen."
  },
  {
    EN: "Please call me.",
    CH: "请给我打电话。",
    JP: "私に電話してください。",
    KO: "저에게 전화해주세요.",
    ES: "Por favor, llámame.",
    DE: "Bitte rufen Sie mich an."
  }
];

export const common = [
  { EN: "Be careful.", JP: "気をつけてください。", CH: "小心。", KO: "조심하세요.", ES: "¡Ten cuidado!", DE: "Sei vorsichtig." },
  { EN: "Be careful driving.", JP: "運転に気をつけてください。", CH: "开车小心。", KO: "운전 조심하세요.", ES: "Ten cuidado al conducir.", DE: "Fahr vorsichtig." },
  { EN: "Can you translate this for me?", JP: "これを翻訳してくれますか？", CH: "你能为我翻译这个吗？", KO: "이것을 번역해 주시겠어요?", ES: "¿Puedes traducir esto para mí?", DE: "Können Sie das für mich übersetzen?" },
  { EN: "Chicago is very different from Boston.", JP: "シカゴはボストンと非常に異なります。", CH: "芝加哥与波士顿非常不同。", KO: "시카고는 보스턴과 매우 다릅니다.", ES: "Chicago es muy diferente de Boston.", DE: "Chicago ist sehr anders als Boston." },
  { EN: "Don't worry.", JP: "心配しないでください。", CH: "别担心。", KO: "걱정하지 마세요.", ES: "No te preocupes.", DE: "Mach dir keine Sorgen." },
  { EN: "Everyone knows it.", JP: "みんなそれを知っています。", CH: "每个人都知道。", KO: "모두가 그것을 압니다.", ES: "Todos lo saben.", DE: "Jeder weiß es." },
  { EN: "Everything is ready.", JP: "すべて準備が整いました。", CH: "一切准备就绪。", KO: "모든 것이 준비되었습니다.", ES: "Todo está listo.", DE: "Alles ist bereit." },
  { EN: "Excellent.", JP: "素晴らしい。", CH: "太棒了。", KO: "훌륭합니다.", ES: "Excelente.", DE: "Ausgezeichnet." },
  { EN: "From time to time.", JP: "時々。", CH: "不时。", KO: "가끔.", ES: "De vez en cuando.", DE: "Von Zeit zu Zeit." },
  { EN: "Good idea.", JP: "良い考えです。", CH: "好主意。", KO: "좋은 생각입니다.", ES: "Buena idea.", DE: "Gute Idee." },
  { EN: "He likes it very much.", JP: "彼はそれがとても好きです。", CH: "他非常喜欢它。", KO: "그는 그것을 매우 좋아합니다.", ES: "Le gusta mucho.", DE: "Er mag es sehr." },
  { EN: "Help!", JP: "助けて！", CH: "救命！", KO: "도와주세요!", ES: "¡Ayuda!", DE: "Hilfe!" },
  { EN: "He's coming soon.", JP: "彼はすぐに来ます。", CH: "他很快就来。", KO: "그는 곧 올 것입니다.", ES: "Él viene pronto.", DE: "Er kommt bald." },
  { EN: "He's right.", JP: "彼は正しいです。", CH: "他是对的。", KO: "그는 맞습니다.", ES: "Él tiene razón.", DE: "Er hat recht." },
  { EN: "He's very annoying.", JP: "彼はとても迷惑です。", CH: "他非常烦人。", KO: "그는 매우 짜증납니다.", ES: "Es muy molesto.", DE: "Er ist sehr nervig." },
  { EN: "He's very famous.", JP: "彼はとても有名です。", CH: "他非常有名。", KO: "그는 매우 유명합니다.", ES: "Él es muy famoso.", DE: "Er ist sehr berühmt." },
  { EN: "How are you?", JP: "お元気ですか？", CH: "你好吗？", KO: "어떻게 지내세요?", ES: "¿Cómo estás?", DE: "Wie geht's?" },
  { EN: "How's work going?", JP: "仕事はどうですか？", CH: "工作进展如何？", KO: "일은 어떻게 되고 있나요?", ES: "¿Cómo va el trabajo?", DE: "Wie läuft die Arbeit?" },
  { EN: "Hurry!", JP: "急いで！", CH: "快点！", KO: "서두르세요!", ES: "¡Apúrate!", DE: "Beeil dich!" },
  { EN: "I ate already.", JP: "もう食べました。", CH: "我已经吃过了。", KO: "저는 이미 먹었습니다.", ES: "Ya comí.", DE: "Ich habe schon gegessen." },
  { EN: "I can't hear you.", JP: "あなたの声が聞こえません。", CH: "我听不见你。", KO: "당신의 목소리가 들리지 않습니다.", ES: "No te oigo.", DE: "Ich kann dich nicht hören." },
  { EN: "I'd like to go for a walk.", JP: "散歩に行きたいです。", CH: "我想去散步。", KO: "산책하고 싶습니다.", ES: "Me gustaría dar un paseo.", DE: "Ich möchte spazieren gehen." },
  { EN: "I don't like him.", JP: "彼が嫌いです。", CH: "我不喜欢他。", KO: "그가 싫어요.", ES: "No me gusta él.", DE: "Ich mag ihn nicht." },
  { EN: "I don't like it.", JP: "それが嫌いです。", CH: "我不喜欢它。", KO: "그게 싫어요.", ES: "No me gusta eso.", DE: "Ich mag es nicht." },
  { EN: "I don't speak very well.", JP: "あまり上手に話せません。", CH: "我说得不太好。", KO: "잘 못 해요.", ES: "No hablo muy bien.", DE: "Ich spreche nicht sehr gut." },
  { EN: "I don't understand.", JP: "わかりません。", CH: "我不明白。", KO: "이해하지 못해요.", ES: "No entiendo.", DE: "Ich verstehe nicht." },
  { EN: "I don't want it.", JP: "それが欲しくありません。", CH: "我不想要它。", KO: "그것 원하지 않아요.", ES: "No lo quiero.", DE: "Ich will es nicht." },
  { EN: "I don't want that.", JP: "それが欲しくありません。", CH: "我不想要那个。", KO: "그것 원하지 않아요.", ES: "No quiero eso.", DE: "Ich will das nicht." },
  { EN: "I don't want to bother you.", JP: "ご迷惑をおかけしたくありません。", CH: "我不想打扰你。", KO: "귀찮게 하고 싶지 않아요.", ES: "No quiero molestarte.", DE: "Ich möchte dich nicht stören." },
  { EN: "I feel good.", JP: "気分が良いです。", CH: "我感觉很好。", KO: "기분이 좋아요.", ES: "Me siento bien.", DE: "Ich fühle mich gut." },
  { EN: "If you need my help, please let me know.", JP: "私の助けが必要なら、お知らせください。", CH: "如果你需要我的帮助，请告诉我。", KO: "내 도움이 필요하면 알려주세요.", ES: "Si necesitas mi ayuda, por favor avísame.", DE: "Wenn du meine Hilfe brauchst, lass es mich bitte wissen." },
  { EN: "I get off of work at 6.", JP: "6時に仕事が終わります。", CH: "我六点下班。", KO: "6시에 퇴근해요.", ES: "Salgo del trabajo a las 6.", DE: "Ich habe um 6 Feierabend." },
  { EN: "I have a headache.", JP: "頭が痛いです。", CH: "我头痛。", KO: "머리가 아파요.", ES: "Tengo dolor de cabeza.", DE: "Ich habe Kopfschmerzen." },
  { EN: "I hope you and your wife have a nice trip.", JP: "あなたと奥様が良い旅行をされますように。", CH: "希望你和你的妻子旅途愉快。", KO: "당신과 아내분이 좋은 여행 되세요.", ES: "Espero que tú y tu esposa tengan un buen viaje.", DE: "Ich hoffe, du und deine Frau habt eine schöne Reise." },
  { EN: "I know.", JP: "知っています。", CH: "我知道。", KO: "알아요.", ES: "Lo sé.", DE: "Ich weiß." },
  { EN: "I like her.", JP: "彼女が好きです。", CH: "我喜欢她。", KO: "그녀가 좋아요.", ES: "Me gusta ella.", DE: "Ich mag sie." },
  { EN: "I'll call you when I leave.", JP: "出発する時に電話します。", CH: "我离开时会打电话给你。", KO: "떠날 때 전화할게요.", ES: "Te llamaré cuando me vaya.", DE: "Ich rufe dich an, wenn ich gehe." },
  { EN: "I'll come back later.", JP: "後で戻ります。", CH: "我稍后会回来。", KO: "나중에 다시 올게요.", ES: "Volveré más tarde.", DE: "Ich komme später zurück." },
  { EN: "I'll pay.", JP: "私が払います。", CH: "我来付钱。", KO: "제가 낼게요.", ES: "Yo pagaré.", DE: "Ich werde bezahlen." },
  { EN: "I'll take it.", JP: "それを取ります。", CH: "我拿这个。", KO: "그거 가져갈게요.", ES: "Lo tomaré.", DE: "Ich nehme es." },
  { EN: "I'll take you to the bus stop.", JP: "バス停までお送りします。", CH: "我送你到公交车站。", KO: "버스 정류장까지 데려다 줄게요.", ES: "Te llevaré a la parada de autobús.", DE: "Ich bringe dich zur Bushaltestelle." },
  { EN: "I lost my watch.", JP: "時計をなくしました。", CH: "我丢了我的手表。", KO: "시계를 잃어버렸어요.", ES: "Perdí mi reloj.", DE: "Ich habe meine Uhr verloren." },
  { EN: "I love you.", JP: "愛しています。", CH: "我爱你。", KO: "사랑해요.", ES: "Te quiero.", DE: "Ich liebe dich." },
  { EN: "I'm an American.", JP: "私はアメリカ人です。", CH: "我是美国人。", KO: "저는 미국인입니다.", ES: "Soy estadounidense.", DE: "Ich bin Amerikaner." },
  { EN: "I'm cleaning my room.", JP: "部屋を掃除しています。", CH: "我在打扫我的房间。", KO: "방 청소하고 있어요.", ES: "Estoy limpiando mi habitación.", DE: "Ich putze mein Zimmer." },
  { EN: "I'm cold.", JP: "寒いです。", CH: "我冷。", KO: "추워요.", ES: "Tengo frío.", DE: "Mir ist kalt." },
  { EN: "I'm coming to pick you up.", JP: "迎えに行きます。", CH: "我来接你。", KO: "데리러 갈게요.", ES: "Voy a recogerte.", DE: "Ich komme dich abholen." },
  { EN: "I'm going to leave.", JP: "出発します。", CH: "我要离开了。", KO: "떠날 거예요.", ES: "Me voy a ir.", DE: "Ich werde gehen." },
  { EN: "I'm good, and you?", JP: "元気です、あなたは？", CH: "我很好，你呢？", KO: "저는 좋아요, 당신은요?", ES: "Estoy bien, ¿y tú?", DE: "Mir geht's gut, und dir?" },
  { EN: "I'm happy.", JP: "幸せです。", CH: "我很高兴。", KO: "행복해요.", ES: "Estoy feliz.", DE: "Ich bin glücklich." },
  { EN: "I'm hungry.", JP: "お腹がすいています。", CH: "我饿了。", KO: "배고파요.", ES: "Tengo hambre.", DE: "Ich habe Hunger." },
  { EN: "I'm married.", JP: "結婚しています。", CH: "我结婚了。", KO: "결혼했어요.", ES: "Estoy casado.", DE: "Ich bin verheiratet." },
  { EN: "I'm not busy.", JP: "忙しくありません。", CH: "我不忙。", KO: "바쁘지 않아요.", ES: "No estoy ocupado.", DE: "Ich bin nicht beschäftigt." },
  { EN: "I'm not married.", JP: "結婚していません。", CH: "我未婚。", KO: "결혼하지 않았어요.", ES: "No estoy casado.", DE: "Ich bin nicht verheiratet." },
  { EN: "I'm not ready yet.", JP: "まだ準備ができていません。", CH: "我还没准备好。", KO: "아직 준비 안 됐어요.", ES: "Aún no estoy listo.", DE: "Ich bin noch nicht bereit." },
  { EN: "I'm not sure.", JP: "確かではありません。", CH: "我不确定。", KO: "잘 모르겠어요.", ES: "No estoy seguro.", DE: "Ich bin mir nicht sicher." },
  { EN: "I'm sorry, we're sold out.", JP: "すみません、売り切れです。", CH: "抱歉，我们卖完了。", KO: "죄송하지만, 매진되었습니다.", ES: "Lo siento, estamos agotados.", DE: "Es tut mir leid, wir sind ausverkauft." },
  { EN: "I'm thirsty.", JP: "喉が渇きました。", CH: "我渴了。", KO: "목말라요.", ES: "Tengo sed.", DE: "Ich habe Durst." },
  { EN: "I'm very busy. I don't have time now.", JP: "とても忙しいです。今は時間がありません。", CH: "我很忙，现在没时间。", KO: "아주 바빠요. 지금 시간이 없어요.", ES: "Estoy muy ocupado. No tengo tiempo ahora.", DE: "Ich bin sehr beschäftigt. Ich habe jetzt keine Zeit." },
  { EN: "I need to change clothes.", JP: "着替える必要があります。", CH: "我需要换衣服。", KO: "옷을 갈아입어야 해요.", ES: "Necesito cambiarme de ropa.", DE: "Ich muss mich umziehen." },
  { EN: "I need to go home.", JP: "家に帰る必要があります。", CH: "我需要回家。", KO: "집에 가야 해요.", ES: "Necesito ir a casa.", DE: "Ich muss nach Hause gehen." },
  { EN: "I only want a snack.", JP: "軽食だけ欲しいです。", CH: "我只想吃点零食。", KO: "간식만 원해요.", ES: "Solo quiero un bocadillo.", DE: "Ich möchte nur einen Snack." },
  { EN: "Is Mr. Smith an American?", JP: "スミスさんはアメリカ人ですか？", CH: "史密斯先生是美国人吗？", KO: "스미스 씨는 미국인인가요?", ES: "¿El Sr. Smith es estadounidense?", DE: "Ist Herr Smith Amerikaner?" },
  { EN: "Is that enough?", JP: "それで十分ですか？", CH: "那够吗？", KO: "그거 충분한가요?", ES: "¿Eso es suficiente?", DE: "Ist das genug?" },
  { EN: "I think it's very good.", JP: "とても良いと思います。", CH: "我觉得很好。", KO: "아주 좋다고 생각해요.", ES: "Creo que es muy bueno.", DE: "Ich finde es sehr gut." },
  { EN: "I think it tastes good.", JP: "美味しいと思います。", CH: "我觉得味道不错。", KO: "맛있다고 생각해요.", ES: "Creo que sabe bien.", DE: "Ich finde, es schmeckt gut." },
  { EN: "I thought the clothes were cheaper.", JP: "服はもっと安いと思いました。", CH: "我以为衣服更便宜。", KO: "옷이 더 싸다고 생각했어요.", ES: "Pensé que la ropa era más barata.", DE: "Ich dachte, die Kleidung wäre günstiger." },
  { EN: "It's longer than 2 miles.", JP: "それは2マイル以上あります。", CH: "它超过两英里。", KO: "2마일보다 길어요.", ES: "Es más largo que 2 millas.", DE: "Es ist länger als 2 Meilen." },
  { EN: "I've been here for two days.", JP: "ここに2日間います。", CH: "我在这里已经两天了。", KO: "여기에 이틀 있었어요.", ES: "He estado aquí durante dos días.", DE: "Ich bin seit zwei Tagen hier." }
];

export const commonTwo = [
  { EN: "I've heard Texas is a beautiful place.", JP: "テキサスは美しい場所だと聞きました。", CH: "我听说德克萨斯是一个美丽的地方。", KO: "텍사스가 아름다운 곳이라고 들었어요.", ES: "He oído que Texas es un lugar hermoso.", DE: "Ich habe gehört, dass Texas ein schöner Ort ist." },
  { EN: "I've never seen that before.", JP: "それを見たことがありません。", CH: "我以前从未见过那个。", KO: "그걸 본 적이 없어요.", ES: "Nunca he visto eso antes.", DE: "Ich habe das noch nie gesehen." },
  { EN: "I was about to leave the restaurant when my friends arrived.", JP: "友達が到着したとき、私はレストランを出ようとしていました。", CH: "当我的朋友到达时，我正准备离开餐厅。", KO: "친구들이 도착했을 때 저는 식당을 막 떠나려 하고 있었어요.", ES: "Estaba a punto de salir del restaurante cuando llegaron mis amigos.", DE: "Ich wollte gerade das Restaurant verlassen, als meine Freunde ankamen." },
  { EN: "Just a little.", JP: "少しだけ。", CH: "只是一点。", KO: "조금만요.", ES: "Solo un poco.", DE: "Nur ein bisschen." },
  { EN: "Just a moment.", JP: "ちょっと待ってください。", CH: "等一下。", KO: "잠시만요.", ES: "Un momento.", DE: "Einen Moment bitte." },
  { EN: "Let me check.", JP: "確認させてください。", CH: "让我查一下。", KO: "확인해 볼게요.", ES: "Déjame comprobarlo.", DE: "Lass mich nachsehen." },
  { EN: "Let me think about it.", JP: "考えさせてください。", CH: "让我考虑一下。", KO: "생각해 볼게요.", ES: "Déjame pensarlo.", DE: "Lass mich darüber nachdenken." },
  { EN: "Let's go have a look.", JP: "見に行きましょう。", CH: "我们去看看吧。", KO: "보러 가요.", ES: "Vamos a echar un vistazo.", DE: "Lass uns mal sehen gehen." },
  { EN: "Let's practice English.", JP: "英語を練習しましょう。", CH: "我们来练习英语吧。", KO: "영어를 연습해요.", ES: "Practiquemos inglés.", DE: "Lass uns Englisch üben." },
  { EN: "May I speak to Mrs. Smith please?", JP: "スミスさんをお願いします。", CH: "我可以和史密斯夫人说话吗？", KO: "스미스 부인과 통화할 수 있을까요?", ES: "¿Puedo hablar con la Sra. Smith, por favor?", DE: "Kann ich bitte mit Frau Smith sprechen?" },
  { EN: "More than that.", JP: "それ以上です。", CH: "比那更多。", KO: "그것보다 더요.", ES: "Más que eso.", DE: "Mehr als das." },
  { EN: "Never mind.", JP: "気にしないで。", CH: "没关系。", KO: "괜찮아요.", ES: "No importa.", DE: "Schon gut." },
  { EN: "Next time.", JP: "次回。", CH: "下次。", KO: "다음에요.", ES: "La próxima vez.", DE: "Beim nächsten Mal." },
  { EN: "No.", JP: "いいえ。", CH: "不。", KO: "아니요.", ES: "No.", DE: "Nein." },
  { EN: "Nonsense.", JP: "ナンセンス。", CH: "胡说。", KO: "말도 안 돼요.", ES: "¡Qué tontería!", DE: "Unsinn." },
  { EN: "No, thank you.", JP: "いいえ、結構です。", CH: "不，谢谢。", KO: "아니요, 괜찮아요.", ES: "No, gracias.", DE: "Nein, danke." },
  { EN: "Nothing else.", JP: "他には何もありません。", CH: "没有别的了。", KO: "다른 건 없어요.", ES: "Nada más.", DE: "Nichts weiter." },
  { EN: "Not recently.", JP: "最近はありません。", CH: "最近没有。", KO: "최근에는 아니에요.", ES: "No recientemente.", DE: "In letzter Zeit nicht." },
  { EN: "Not yet.", JP: "まだです。", CH: "还没有。", KO: "아직 아니에요.", ES: "Todavía no.", DE: "Noch nicht." },
  { EN: "Of course.", JP: "もちろん。", CH: "当然。", KO: "물론이죠.", ES: "Por supuesto.", DE: "Natürlich." },
  { EN: "Okay.", JP: "わかりました。", CH: "好。", KO: "알겠습니다.", ES: "Está bien.", DE: "Okay." },
  { EN: "Please fill out this form.", JP: "このフォームにご記入ください。", CH: "请填写这张表格。", KO: "이 양식을 작성해주세요.", ES: "Por favor, rellene este formulario.", DE: "Bitte füllen Sie dieses Formular aus." },
  { EN: "Please take me to this address.", JP: "この住所まで連れて行ってください。", CH: "请带我到这个地址。", KO: "이 주소까지 데려다 주세요.", ES: "Llévame a esta dirección, por favor.", DE: "Bitte bringen Sie mich zu dieser Adresse." },
  { EN: "Please write it down.", JP: "書いてください。", CH: "请写下来。", KO: "적어주세요.", ES: "Por favor, escríbelo.", DE: "Bitte schreiben Sie es auf." },
  { EN: "Really?", JP: "本当ですか？", CH: "真的吗？", KO: "정말요?", ES: "¿De verdad?", DE: "Wirklich?" },
  { EN: "Right here.", JP: "ここです。", CH: "就在这里。", KO: "바로 여기요.", ES: "Justo aquí.", DE: "Hier." },
  { EN: "Right there.", JP: "あそこです。", CH: "在那里。", KO: "저기요.", ES: "Justo allí.", DE: "Dort." },
  { EN: "See you later.", JP: "また後で。", CH: "回头见。", KO: "나중에 봐요.", ES: "Hasta luego.", DE: "Bis später." },
  { EN: "See you tomorrow.", JP: "また明日。", CH: "明天见。", KO: "내일 봐요.", ES: "Hasta mañana.", DE: "Bis morgen." },
  { EN: "See you tonight.", JP: "今夜会いましょう。", CH: "今晚见。", KO: "오늘 밤에 봐요.", ES: "Nos vemos esta noche.", DE: "Bis heute Abend." },
  { EN: "She's pretty.", JP: "彼女はきれいです。", CH: "她很漂亮。", KO: "그녀는 예뻐요.", ES: "Ella es bonita.", DE: "Sie ist hübsch." },
  { EN: "Sorry to bother you.", JP: "お邪魔してすみません。", CH: "打扰了，对不起。", KO: "귀찮게 해서 죄송해요.", ES: "Perdón por molestarte.", DE: "Entschuldigung, dass ich störe." },
  { EN: "Stop!", JP: "止まって！", CH: "停！", KO: "멈춰요!", ES: "¡Alto!", DE: "Stopp!" },
  { EN: "Take a chance.", JP: "チャンスをつかみましょう。", CH: "抓住机会。", KO: "기회를 잡아요.", ES: "Aprovecha la oportunidad.", DE: "Nutze die Chance." },
  { EN: "Take it outside.", JP: "外に持って行ってください。", CH: "拿到外面去。", KO: "밖으로 가져가요.", ES: "Llévalo afuera.", DE: "Nimm es nach draußen." },
  { EN: "Tell me.", JP: "教えてください。", CH: "告诉我。", KO: "말해 주세요.", ES: "Dime.", DE: "Sag mir." },
  { EN: "Thanks for everything.", JP: "すべてありがとう。", CH: "谢谢你的一切。", KO: "모든 것에 감사해요.", ES: "Gracias por todo.", DE: "Danke für alles." },
  { EN: "Thanks for your help.", JP: "助けてくれてありがとう。", CH: "谢谢你的帮助。", KO: "도와줘서 고마워요.", ES: "Gracias por tu ayuda.", DE: "Danke für deine Hilfe." },
  { EN: "Thank you.", JP: "ありがとう。", CH: "谢谢。", KO: "감사합니다.", ES: "Gracias.", DE: "Danke." },
  { EN: "Thank you miss.", JP: "ありがとうございます、小姐。", CH: "谢谢你，小姐。", KO: "감사합니다, 아가씨.", ES: "Gracias, señorita.", DE: "Danke, Fräulein." },
  { EN: "Thank you sir.", JP: "ありがとうございます、先生。", CH: "谢谢您，先生。", KO: "감사합니다, 선생님.", ES: "Gracias, señor.", DE: "Danke, Herr." },
  { EN: "Thank you very much.", JP: "どうもありがとうございます。", CH: "非常感谢。", KO: "정말 감사합니다.", ES: "Muchas gracias.", DE: "Vielen Dank." },
  { EN: "That looks great.", JP: "それは素晴らしいですね。", CH: "那看起来很棒。", KO: "좋아 보여요.", ES: "Eso se ve genial.", DE: "Das sieht großartig aus." },
  { EN: "That's alright.", JP: "大丈夫です。", CH: "没关系。", KO: "괜찮아요.", ES: "Está bien.", DE: "Das ist in Ordnung." },
  { EN: "That's enough.", JP: "それで十分です。", CH: "够了。", KO: "그거면 충분해요.", ES: "Eso es suficiente.", DE: "Das reicht." },
  { EN: "That's fine.", JP: "それでいいです。", CH: "那很好。", KO: "좋아요.", ES: "Está bien.", DE: "Das ist gut." },
  { EN: "That's it.", JP: "それです。", CH: "就是这样。", KO: "그게 전부예요.", ES: "Eso es todo.", DE: "Das ist es." },
  { EN: "That smells bad.", JP: "それは臭いです。", CH: "那闻起来很难闻。", KO: "그거 냄새 나요.", ES: "Eso huele mal.", DE: "Das riecht schlecht." },
  { EN: "That's not fair.", JP: "それは不公平です。", CH: "那不公平。", KO: "그건 공평하지 않아요.", ES: "Eso no es justo.", DE: "Das ist nicht fair." },
  { EN: "That's not right.", JP: "それは正しくありません。", CH: "那不对。", KO: "그건 맞지 않아요.", ES: "Eso no está bien.", DE: "Das stimmt nicht." },
  { EN: "That's right.", JP: "その通りです。", CH: "那是对的。", KO: "그게 맞아요.", ES: "Eso es correcto.", DE: "Das stimmt." },
  { EN: "That's too bad.", JP: "それは残念です。", CH: "那太糟了。", KO: "그거 안타깝네요.", ES: "Qué mal.", DE: "Das ist schade." },
  { EN: "That's too many.", JP: "多すぎます。", CH: "那太多了。", KO: "너무 많아요.", ES: "Eso son demasiados.", DE: "Das sind zu viele." },
  { EN: "That's too much.", JP: "それは多すぎます。", CH: "那太多了。", KO: "그거 너무 많아요.", ES: "Eso es demasiado.", DE: "Das ist zu viel." },
  { EN: "The book is under the table.", JP: "本はテーブルの下にあります。", CH: "书在桌子下面。", KO: "책이 탁자 밑에 있어요.", ES: "El libro está debajo de la mesa.", DE: "Das Buch liegt unter dem Tisch." },
  { EN: "They'll be right back.", JP: "すぐ戻ります。", CH: "他们马上回来。", KO: "곧 돌아올 거예요.", ES: "Ellos volverán enseguida.", DE: "Sie sind gleich zurück." },
  { EN: "They're the same.", JP: "それらは同じです。", CH: "它们是一样的。", KO: "같아요.", ES: "Son iguales.", DE: "Sie sind gleich." },
  { EN: "They're very busy.", JP: "とても忙しいです。", CH: "他们非常忙。", KO: "그들은 아주 바빠요.", ES: "Están muy ocupados.", DE: "Sie sind sehr beschäftigt." },
  { EN: "This doesn't work.", JP: "これはうまくいきません。", CH: "这个不行。", KO: "이거 안 돼요.", ES: "Esto no funciona.", DE: "Das funktioniert nicht." },
  { EN: "This is very difficult.", JP: "これはとても難しいです。", CH: "这很难。", KO: "이거 매우 어려워요.", ES: "Esto es muy difícil.", DE: "Das ist sehr schwierig." },
  { EN: "This is very important.", JP: "これはとても重要です。", CH: "这很重要。", KO: "이거 매우 중요해요.", ES: "Esto es muy importante.", DE: "Das ist sehr wichtig." },
  { EN: "Try it.", JP: "やってみてください。", CH: "试试吧。", KO: "해보세요.", ES: "Pruébalo.", DE: "Probier es." },
  { EN: "Very good, thanks.", JP: "とても良いです、ありがとう。", CH: "很好，谢谢。", KO: "아주 좋아요, 감사합니다.", ES: "Muy bien, gracias.", DE: "Sehr gut, danke." },
  { EN: "We like it very much.", JP: "私たちはそれがとても好きです。", CH: "我们非常喜欢它。", KO: "우리는 그것을 아주 좋아해요.", ES: "Nos gusta mucho.", DE: "Wir mögen es sehr." },
  { EN: "Would you take a message please?", JP: "伝言をお願いします。", CH: "请留言好吗？", KO: "메시지를 받아 주시겠어요?", ES: "¿Podría tomar un mensaje, por favor?", DE: "Könnten Sie bitte eine Nachricht entgegennehmen?" },
  { EN: "Yes, really.", JP: "はい、本当に。", CH: "是的，真的。", KO: "네, 정말이에요.", ES: "Sí, de verdad.", DE: "Ja, wirklich." },
  { EN: "You're beautiful.", JP: "あなたは美しいです。", CH: "你很漂亮。", KO: "당신은 아름다워요.", ES: "Eres hermosa.", DE: "Du bist schön." },
  { EN: "You're very nice.", JP: "あなたはとても親切です。", CH: "你很友好。", KO: "당신은 정말 친절해요.", ES: "Eres muy amable.", DE: "Du bist sehr nett." },
  { EN: "You're very smart.", JP: "あなたはとても賢いです。", CH: "你很聪明。", KO: "당신은 매우 똑똑해요.", ES: "Eres muy inteligente.", DE: "Du bist sehr klug." },
  { EN: "Your things are all here.", JP: "あなたのものは全部揃っています。", CH: "你的东西都在这里。", KO: "당신의 물건이 모두 여기 있어요.", ES: "Tus cosas están todas aquí.", DE: "Deine Sachen sind alle hier." }
];


export const travel = [
  
  { EN: "About 300 kilometers.", JP: "約300キロです。", CH: "大约300公里。", KO: "약 300킬로미터예요.", ES: "Unos 300 kilómetros.", DE: "Etwa 300 Kilometer." },
  { EN: "A one way ticket.", JP: "片道切符です。", CH: "单程票。", KO: "편도 표예요.", ES: "Un billete de ida.", DE: "Ein Einzelfahrschein." },
  { EN: "Are you going to help her?", JP: "彼女を手伝いますか？", CH: "你打算帮她吗？", KO: "그녀를 도와줄 거예요?", ES: "¿Vas a ayudarla?", DE: "Wirst du ihr helfen?" },
  { EN: "A round trip ticket.", JP: "往復切符です。", CH: "往返票。", KO: "왕복 표예요.", ES: "Un billete de ida y vuelta.", DE: "Eine Hin- und Rückfahrkarte." },
  { EN: "At what time?", JP: "何時ですか？", CH: "几点？", KO: "몇 시에요?", ES: "¿A qué hora?", DE: "Um wieviel Uhr?" },
  { EN: "Can I make an appointment for next Wednesday?", JP: "来週の水曜日に予約できますか？", CH: "我可以预约下周三吗？", KO: "다음 수요일에 예약할 수 있을까요?", ES: "¿Puedo hacer una cita para el próximo miércoles?", DE: "Kann ich einen Termin für nächsten Mittwoch vereinbaren?" },
  { EN: "Can you repeat that please?", JP: "もう一度言ってください。", CH: "请再说一遍。", KO: "다시 말해 주세요.", ES: "¿Puedes repetir eso, por favor?", DE: "Können Sie das bitte wiederholen?" },
  { EN: "Does this road go to New York?", JP: "この道はニューヨークに行きますか？", CH: "这条路通往纽约吗？", KO: "이 길이 뉴욕으로 가나요?", ES: "¿Esta carretera va a Nueva York?", DE: "Führt diese Straße nach New York?" },
  { EN: "Do you have enough money?", JP: "お金は十分ですか？", CH: "你有足够的钱吗？", KO: "돈이 충분해요?", ES: "¿Tienes suficiente dinero?", DE: "Hast du genug Geld?" },
  { EN: "Do you know how to cook?", JP: "料理の仕方を知っていますか？", CH: "你会做饭吗？", KO: "요리할 줄 알아요?", ES: "¿Sabes cocinar?", DE: "Kannst du kochen?" },
  { EN: "Do you know what this says?", JP: "これは何と書いてあるか知っていますか？", CH: "你知道这是什么意思吗？", KO: "이게 뭐라고 적혀 있는지 알아요?", ES: "¿Sabes lo que dice esto?", DE: "Weißt du, was das heißt?" },
  { EN: "Do you want me to come and pick you up?", JP: "迎えに行きましょうか？", CH: "你想让我来接你吗？", KO: "마중 나가 줄까요?", ES: "¿Quieres que vaya a recogerte?", DE: "Willst du, dass ich dich abhole?" },
  { EN: "Follow me.", JP: "ついて来てください。", CH: "跟我来。", KO: "저를 따라오세요.", ES: "Sígueme.", DE: "Folge mir." },
  { EN: "From here to there.", JP: "ここからそこまで。", CH: "从这里到那里。", KO: "여기서 저기까지.", ES: "De aquí a allí.", DE: "Von hier dorthin." },
  { EN: "Go straight ahead.", JP: "まっすぐ行ってください。", CH: "一直向前走。", KO: "직진하세요.", ES: "Sigue recto.", DE: "Gehen Sie geradeaus." },
  { EN: "Have you arrived?", JP: "到着しましたか？", CH: "你到达了吗？", KO: "도착했어요?", ES: "¿Has llegado?", DE: "Bist du angekommen?" },
  { EN: "Have you been to Boston?", JP: "ボストンに行ったことがありますか？", CH: "你去过波士顿吗？", KO: "보스턴에 가본 적 있어요?", ES: "¿Has estado en Boston?", DE: "Warst du schon in Boston?" },
  { EN: "How do I get there?", JP: "どうやって行けばいいですか？", CH: "我怎么去那里？", KO: "거기 어떻게 가요?", ES: "¿Cómo llego allí?", DE: "Wie komme ich dorthin?" },
  { EN: "How do I get to Daniel Street?", JP: "ダニエル通りにはどう行けばいいですか？", CH: "我怎么去丹尼尔街？", KO: "다니엘 스트리트에 어떻게 가요?", ES: "¿Cómo llego a la calle Daniel?", DE: "Wie komme ich zur Daniel Street?" },
  { EN: "How do I get to the American Embassy?", JP: "アメリカ大使館にはどう行けばいいですか？", CH: "我怎么去美国大使馆？", KO: "미국 대사관에 어떻게 가요?", ES: "¿Cómo llego a la Embajada de Estados Unidos?", DE: "Wie komme ich zur amerikanischen Botschaft?" },
  { EN: "How long does it take by car?", JP: "車でどのくらいかかりますか？", CH: "开车需要多久？", KO: "차로 얼마나 걸려요?", ES: "¿Cuánto se tarda en coche?", DE: "Wie lange dauert es mit dem Auto?" },
  { EN: "How long does it take to get to Georgia?", JP: "ジョージアまでどのくらいかかりますか？", CH: "到乔治亚需要多久？", KO: "조지아까지 얼마나 걸려요?", ES: "¿Cuánto se tarda en llegar a Georgia?", DE: "Wie lange dauert es, nach Georgia zu kommen?" },
  { EN: "How long is the flight?", JP: "飛行時間はどのくらいですか？", CH: "飞行多长时间？", KO: "비행 시간이 얼마나 돼요?", ES: "¿Cuánto dura el vuelo?", DE: "Wie lange dauert der Flug?" },
  { EN: "How was the movie?", JP: "映画はどうでしたか？", CH: "电影怎么样？", KO: "영화 어땠어요?", ES: "¿Qué tal fue la película?", DE: "Wie war der Film?" },
  { EN: "I'd like to make a phone call.", JP: "電話をかけたいです。", CH: "我想打个电话。", KO: "전화하고 싶어요.", ES: "Quisiera hacer una llamada.", DE: "Ich möchte telefonieren." },
  { EN: "I'd like to make a reservation.", JP: "予約をしたいです。", CH: "我想预订。", KO: "예약하고 싶어요.", ES: "Quisiera hacer una reserva.", DE: "Ich möchte eine Reservierung machen." },
  { EN: "I have a question I want to ask you./ I want to ask you a question.", JP: "質問があります。", CH: "我有一个问题想问你。", KO: "질문이 있어요.", ES: "Tengo una pregunta.", DE: "Ich habe eine Frage." },
  { EN: "I'll take that one also.", JP: "それもください。", CH: "我也要那个。", KO: "그것도 할게요.", ES: "Tomaré ese también.", DE: "Ich nehme das auch." },
  { EN: "I'm coming right now.", JP: "今すぐ行きます。", CH: "我现在就来。", KO: "지금 바로 갈게요.", ES: "Voy ahora mismo.", DE: "Ich komme sofort." },
  { EN: "I'm going home in four days.", JP: "4日後に帰国します。", CH: "我四天后回家。", KO: "4일 후에 집에 가요.", ES: "Me voy a casa en cuatro días.", DE: "Ich gehe in vier Tagen nach Hause." },
  { EN: "I'm leaving Tomorrow.", JP: "明日出発します。", CH: "我明天离开。", KO: "내일 떠나요.", ES: "Me voy mañana.", DE: "Ich gehe morgen." },
  { EN: "I'm looking for the post office.", JP: "郵便局を探しています。", CH: "我在找邮局。", KO: "우체국을 찾고 있어요.", ES: "Estoy buscando la oficina de correos.", DE: "Ich suche das Postamt." },
  { EN: "Is this pen yours?", JP: "このペンはあなたのですか？", CH: "这支笔是你的吗？", KO: "이 펜은 당신 거예요?", ES: "¿Es este bolígrafo tuyo?", DE: "Ist dieser Stift deiner?" },
  { EN: "I wish I had one.", JP: "一つ持っていたらなあ。", CH: "我希望我有一个。", KO: "하나 있었으면 좋겠어요.", ES: "Ojalá tuviera uno.", DE: "Ich wünschte, ich hätte einen." },
  { EN: "One ticket to New York please.", JP: "ニューヨークまでの切符を一枚ください。", CH: "请给我一张去纽约的票。", KO: "뉴욕행 티켓 한 장 주세요.", ES: "Un billete a Nueva York, por favor.", DE: "Ein Ticket nach New York, bitte." },
  { EN: "One way or round trip?", JP: "片道ですか、往復ですか？", CH: "单程还是往返？", KO: "편도인가요, 왕복인가요?", ES: "¿Solo ida o ida y vuelta?", DE: "Einfach oder Hin- und Rückfahrt?" },
  { EN: "Please speak slower.", JP: "もっとゆっくり話してください。", CH: "请说慢一点。", KO: "좀 더 천천히 말해주세요.", ES: "Por favor, habla más despacio.", DE: "Bitte sprechen Sie langsamer." },
  { EN: "Please take me to the airport.", JP: "空港まで連れて行ってください。", CH: "请带我去机场。", KO: "공항까지 데려다 주세요.", ES: "Llévame al aeropuerto, por favor.", DE: "Bitte bringen Sie mich zum Flughafen." },
  { EN: "That way.", JP: "あちらです。", CH: "那边。", KO: "저쪽이에요.", ES: "Por allí.", DE: "Dort entlang." },
  { EN: "The plane departs at 5:30P.", JP: "飛行機は午後5時30分に出発します。", CH: "飞机下午5:30起飞。", KO: "비행기는 오후 5시 30분에 출발해요.", ES: "El avión sale a las 5:30 p.m.", DE: "Das Flugzeug startet um 17:30 Uhr." },
  { EN: "They arrived yesterday.", JP: "彼らは昨日到着しました。", CH: "他们昨天到了。", KO: "그들은 어제 도착했어요.", ES: "Llegaron ayer.", DE: "Sie sind gestern angekommen." },
  { EN: "Turn around.", JP: "回れ！", CH: "掉头。", KO: "돌아가세요.", ES: "Da la vuelta.", DE: "Dreh um." },
  { EN: "Turn left.", JP: "左に曲がってください。", CH: "左转。", KO: "왼쪽으로 도세요.", ES: "Gira a la izquierda.", DE: "Links abbiegen." },
  { EN: "Turn right.", JP: "右に曲がってください。", CH: "右转。", KO: "오른쪽으로 도세요.", ES: "Gira a la derecha.", DE: "Rechts abbiegen." },
   { EN: "What time are you going to the bus station?", JP: "何時にバス停に行きますか？", CH: "你什么时候去公交站？", KO: "버스 정류장에 몇 시에 가요?", ES: "¿A qué hora vas a la estación de autobuses?", DE: "Um wieviel Uhr gehst du zur Busstation?" },
  { EN: "When did this happen?", JP: "これはいつ起こりましたか？", CH: "这是什么时候发生的？", KO: "이게 언제 일어났어요?", ES: "¿Cuándo pasó esto?", DE: "Wann ist das passiert?" },
  { EN: "When did you arrive in Boston?", JP: "ボストンにはいつ到着しましたか？", CH: "你什么时候到波士顿的？", KO: "보스턴에는 언제 도착했어요?", ES: "¿Cuándo llegaste a Boston?", DE: "Wann bist du in Boston angekommen?" },
  { EN: "When does he arrive?", JP: "彼はいつ到着しますか？", CH: "他什么时候到达？", KO: "그는 언제 도착해요?", ES: "¿Cuándo llega él?", DE: "Wann kommt er an?" },
  { EN: "When does it arrive?", JP: "それはいつ到着しますか？", CH: "它什么时候到达？", KO: "그건 언제 도착해요?", ES: "¿Cuándo llega?", DE: "Wann kommt es an?" },
  { EN: "When does the bank open?", JP: "銀行は何時に開きますか？", CH: "银行什么时候开门？", KO: "은행은 언제 열어요?", ES: "¿Cuándo abre el banco?", DE: "Wann öffnet die Bank?" },
  { EN: "When does the bus leave?", JP: "バスは何時に出発しますか？", CH: "公交车什么时候发车？", KO: "버스는 언제 출발해요?", ES: "¿Cuándo sale el autobús?", DE: "Wann fährt der Bus ab?" },
  { EN: "When do we arrive?", JP: "私たちはいつ到着しますか？", CH: "我们什么时候到达？", KO: "우리는 언제 도착해요?", ES: "¿Cuándo llegamos?", DE: "Wann kommen wir an?" },
  { EN: "When do we leave?", JP: "私たちはいつ出発しますか？", CH: "我们什么时候离开？", KO: "우리는 언제 떠나요?", ES: "¿Cuándo nos vamos?", DE: "Wann fahren wir ab?" },
  { EN: "Where can I mail this?", JP: "これはどこに出せますか？", CH: "我可以在哪里寄这个？", KO: "이거 어디에서 보낼 수 있어요?", ES: "¿Dónde puedo enviar esto?", DE: "Wo kann ich das verschicken?" },
  { EN: "Where is she from?", JP: "彼女はどこの出身ですか？", CH: "她来自哪里？", KO: "그녀는 어디 출신이에요?", ES: "¿De dónde es ella?", DE: "Woher kommt sie?" },
  { EN: "Where is the bathroom?", JP: "トイレはどこですか？", CH: "洗手间在哪里？", KO: "화장실이 어디에요?", ES: "¿Dónde está el baño?", DE: "Wo ist die Toilette?" },
  { EN: "Why not?", JP: "なぜだめですか？", CH: "为什么不呢？", KO: "왜 안 돼요?", ES: "¿Por qué no?", DE: "Warum nicht?" },
  { EN: "Will you remind me?", JP: "思い出させてくれますか？", CH: "你会提醒我吗？", KO: "저에게 알려줄래요?", ES: "¿Me lo recordarás?", DE: "Wirst du mich daran erinnern?" }
  
]
